const seededDataFood = [
    {
        dishName: "Seared Lemon Pepper Salmon with Arugula Salad",
        ingredients: ["2 Salmon Fillets","2 pinches Sea Salt","1 pinch Lemon Pepper","2 cups Arugula","½ Red Onion , thinly sliced","8 Cherry Tomatoes , halved","1 pinch Freshly Ground Black Pepper","3 Tbsp Extra-Virgin Olive Oil","to taste Lemons , sliced"],
        cuisine: "American",
        recipe: "On two plates, add a handful of Arugula (2 cups) to each one. Evenly divide the Red Onion (1/2) and Cherry Tomatoes (8) on top of the arugula. Season with Sea Salt (1 pinch) and Freshly Ground Black Pepper (1 pinch) and set aside. Season Salmon Fillets (2) with Sea Salt (1 pinch) and a generous pinch of Lemon Pepper (1 pinch) seasoning. Compress the seasonings with your hands so they stick to the salmon. Heat a frying pan with a medium-high heat and add Extra-Virgin Olive Oil (2 Tbsp). After 2 minutes, add the fillets of salmon seasoned side down. Using a spatula, push down on each fillet for about 30 seconds. Then after 3 minutes, flip the salmon fillets to cook the other side. Cook for a total of 6 minutes, then remove the salmon from the heat. Add 1 fillet to each plate with the salad, garnish with a couple of slices of Lemons (to taste) and add a drizzle of Extra-Virgin Olive Oil (1 Tbsp) to the salad before serving.",
        dishVideo: "https://www.youtube.com/watch?v=T5uDIHYT1n0&ab_channel=SpainonaFork"
    },{
        dishName: "Quick Shrimp Stir Fry",
        ingredients: ["3 tablespoons sesame oil, 1 pound shrimp, deveined and shelled (or tail on), wild caught if possible, 1 pound broccoli or broccolini (stem on), about 4 cups, 2 bell peppers, any color, 4 ounces shiitake mushrooms (optional), 2 green onions, 1 tablespoon minced ginger, optional"],
        cuisine: "Asian",
        recipe: "Thaw the shrimp, if frozen. Chop the veggies: Chop the broccoli. Thinly slice the bell peppers. Remove the stems of the shiitake mushrooms and slice (or if using baby shiitakes, you can leave the stems on). Make the stir fry sauce: Whisk together all ingredients until a smooth sauce forms.Cook the vegetables: In a large skillet, heat 2 tablespoons oil over medium high heat. Add the broccoli or broccolini, bell pepper and mushrooms. Add 2 pinches kosher salt and cook 5 to 6 minutes, stirring occasionally, until crisp tender. Remove the vegetables to bowl. Cook the shrimp: Add the additional 1 tablespoon sesame oil to the pan. Add the shrimp and green onions. Cook for 1 to 2 minutes until the shrimp are almost opaque, turning once. Then add back the vegetables and the sauce. Reduce the heat to low and cook until the sauce is thickened",
        dishVideo: ""
    },{
        dishName: "Epic Vegetarian Fajitas",
        ingredients: ["3 bell peppers (red, yellow, green), 1 medium red onion, 2 portobello mushrooms, 4 tablespoons oil divided, 1 ½ teaspoons kosher salt, divided, 3 cloves smashed garlic, 2 teaspoons cumin, 1 each teaspoon chili powder, garlic powder, and smoked paprika, ¼ teaspoon black pepper, 2 15-ounce cans pinto beans, 1 recipe Homemade Fajita Sauce*, Small tortillas"],
        cuisine: "Tex-Mex",
        recipe: "Broil the veggies: Preheat a broiler. Thinly slice the bell peppers and thinly slice the onion. Remove the stems and slice the portobello mushrooms. Place them in a bowl and toss with 2 tablespoons oil and 1 teaspoon kosher salt. Spread the veggies on a parchment lined sheet pan. Place in the broiler and broil 8 to 10 minutes, stirring halfway through, until softened and blackened on some edges. Then go right to Step 3. Cook the beans: Meanwhile in a skillet, whisk together the ingredients for the Homemade Fajita Sauce. Drain and rinse the pinto beans and add them to the skillet. Heat over medium heat and cook until warmed through and the sauce is thickened, about 6 to 8 minutes. Taste and stir in another ¼ teaspoon kosher salt. Saute the veggies: Once the veggies are done in the broiler, finish them on the stove by heating the remaining 2 tablespoons oil in a cast iron skillet or large non-stick skillet over medium high heat. Add the broiled veggies, smashed garlic cloves, cumin, chili powder, garlic powder, smoked paprika, and the remaining ½ teaspoon kosher salt. Cook for 5 minutes, stirring occasionally, until the veggies are tender. Remove and discard the garlic cloves before serving. Warm the tortillas: Warm and char the tortillas by placing them on an open gas flame on medium for a few seconds per side, flipping with tongs, until they are slightly blackened and warm. (See How to Warm Tortillas.) Serve: Place bowls of fajita veggies and pinto beans on the table, with tortillas, sour cream, pico de gallo, guacamole, and fresh cilantro. Let each person add their desired toppings and serve. ",
        dishVideo: ""
    }
]

module.exports = seededDataFood;